---

- hosts: dns_servers
  serial: 1
  tasks:
    - name: Clean dnf cache
      command: dnf clean all
      become: yes
      become_user: root
      become_method: sudo

    - name: Update the node
      dnf:
        name: "*"
        state: latest
        update_cache: yes

    - name: Reboot the node
      reboot:
        post_reboot_delay: 10
  roles:
    - role: dns
      vars:
        primary_dns: 1.1.1.1    # cloudflare
        secondary_dns: 8.8.8.8  # google
        domain: xn--h1admmf5m.xn--d1aqf # костић.дом
        dns_master: xn--80aueki.xn--h1admmf5m.xn--d1aqf # марко.костић.дом
        dns_port: 53
    - role: loadbalancer

- hosts: registries
  serial: 1
  tasks:
    - name: Clean dnf cache
      command: dnf clean all
      become: yes
      become_user: root
      become_method: sudo

    - name: Update the node
      dnf:
        name: "*"
        state: latest
        update_cache: yes

    - name: Reboot the node
      reboot:
        post_reboot_delay: 15

# TODO: Implement proper update procedure for k8s_controllers:k8s_workers_generic
- hosts: k8s_workers_generic:k8s_workers_storage:k8s_controllers
  serial: 1
  tasks:
    - name: Stop Kubelet
      systemd:
        name: kubelet
        state: stopped

    - name: Stop Docker
      systemd:
        name: docker
        state: stopped

    - name: Clean dnf cache
      command: dnf clean all
      become: yes
      become_user: root
      become_method: sudo

    - name: Update the node
      dnf:
        name: "*"
        state: latest
        update_cache: yes

    - name: Reboot the node
      reboot:
        post_reboot_delay: 120

- hosts: mirrors
  tasks:
    - name: Clean dnf cache
      command: dnf clean all
      become: yes
      become_user: root
      become_method: sudo

    - name: Update the node
      dnf:
        name: "*"
        state: latest
        update_cache: yes

    - name: Disable the httpd welcome page
      file:
        path: /etc/httpd/conf.d/welcome.conf
        state: absent

    - name: Restart httpd
      systemd:
        name: httpd
        state: restarted

    - name: Reboot the node
      reboot:
        post_reboot_delay: 10
